Repository comphack/comp_hack, pull requests merged in 2018-05, with the labels that each got.

#493 [FIX] Race condition in the message queue.
  debian/changelog
  docs/guide/setup/website/main.xml
  libcomp/src/Constants.h
  libcomp/src/MessageQueue.h
Labels: bug

#494 [ADD] Support for a world server on a different port.
  CMakeLists.txt
  debian/changelog
  docs/guide/setup/website/main.xml
  libcomp/src/Constants.h
  libcomp/src/LobbyConnection.cpp
  libcomp/src/LobbyConnection.h
  libcomp/src/MessageQueue.h
  server/world/src/WorldServer.cpp
Labels: bug, enhancement

#495 Demon equipment, blacklist, quest bonuses
  contrib/testing/constants.xml
  libcomp/CMakeLists.txt
  libcomp/schema/account.xml
  libcomp/schema/binarydata/devilequipmentdata.xml
  libcomp/schema/demon.xml
  libcomp/schema/master.xml
  libcomp/schema/reportedplayer.xml
  libcomp/schema/tokusei.xml
  libcomp/src/Constants.h
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libcomp/src/PacketCodes.h
  libcomp/src/PersistentObject.cpp
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/CMakeLists.txt
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/DemonState.cpp
  server/channel/src/DemonState.h
  server/channel/src/EventManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/Packets.h
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
  server/channel/src/packets/game/Analyze.cpp
  server/channel/src/packets/game/Barter.cpp
  server/channel/src/packets/game/Blacklist.cpp
  server/channel/src/packets/game/BlacklistUpdate.cpp
  server/channel/src/packets/game/DemonEquip.cpp
  server/channel/src/packets/game/ItemDisassemble.cpp
  server/channel/src/packets/game/MaterialInsert.cpp
  server/channel/src/packets/game/ReportPlayer.cpp
  tools/capfilter/src/ShopFilter.cpp
  tools/capfilter/src/ZoneFilter.cpp
  tools/map/src/main.cpp
Labels: enhancement

#497 Weapon crafting, item mixing and tarot/soul making
  contrib/testing/constants.xml
  libcomp/CMakeLists.txt
  libcomp/schema/binarydata/blenddata.xml
  libcomp/schema/binarydata/synthesisdata.xml
  libcomp/schema/master.xml
  libcomp/src/Constants.h
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libcomp/src/PacketCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/CMakeLists.txt
  server/channel/schema/clientstate.xml
  server/channel/schema/entitystate.xml
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ChatManager.cpp
  server/channel/src/Packets.h
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/EntrustRequest.cpp
  server/channel/src/packets/game/EquipmentMod.cpp
  server/channel/src/packets/game/EquipmentModEdit.cpp
  server/channel/src/packets/game/ItemDisassemble.cpp
  server/channel/src/packets/game/ItemMix.cpp
  server/channel/src/packets/game/ShopRepair.cpp
  server/channel/src/packets/game/Synthesize.cpp
  server/channel/src/packets/game/SynthesizeRecipe.cpp
  server/channel/src/packets/game/TriFusionAccept.cpp
  server/channel/src/packets/game/TriFusionDemonUpdate.cpp
  server/channel/src/packets/game/TriFusionRewardAccept.cpp
Labels: enhancement

#499 [FIX] Coverity was not running with the build matrix
  .travis.yml
  server/channel/src/EventManager.cpp
  server/channel/src/packets/game/DemonCrystallize.cpp
  tools/capfilter/src/main.cpp
  tools/capgrep/src/MainWindow.cpp
  tools/capgrep/src/MainWindow.h
Labels: bug

#500 [ADD] EventDirectionData to bdpatch (for cutscenes)
  debian/changelog
  debian/control
  libcomp/CMakeLists.txt
  libcomp/schema/binarydata/eventdirectiondata.xml
  libcomp/schema/master.xml
  server/channel/src/ActionManager.cpp
  tools/bdpatch/src/main.cpp
Labels: enhancement
