Repository comphack/comp_hack, pull requests merged in 2018-04, with the labels that each got.

#475 Fixing some implicit script bindings and buggy skill results
  debian/changelog
  libcomp/src/Constants.h
  server/channel/src/CharacterState.cpp
  server/channel/src/DemonState.cpp
  server/channel/src/EnemyState.cpp
  server/channel/src/SkillManager.cpp
Labels: bug

#476 [FIX] Float rounding error that caused the client version check to fail.
  CMakeLists.txt
  server/lobby/src/AccountManager.cpp
  server/lobby/src/LoginWebHandler.cpp
  server/lobby/src/packets/game/Login.cpp
Labels: bug

#478 Linux server documentation
  debian/changelog
  docs/guide/architecture/main.xml
  docs/guide/architecture/overview.xml
  docs/guide/binarydata/main.xml
  docs/guide/binarydata/mitamaunionbonus.xml
  docs/guide/book.xml
  docs/guide/components/devilforce.xml
  docs/guide/components/main.xml
  docs/guide/components/shortcuts.xml
  docs/guide/intro/main.xml
  docs/guide/protocol/channel.xml
  docs/guide/protocol/main.xml
  docs/guide/setup/linux/main.xml
  docs/guide/setup/main.xml
  docs/guide/setup/require/main.xml
  docs/guide/static/project_overview.png
  docs/guide/static/shortcut_bar.png
  libcomp/src/Log.cpp
  libcomp/src/TcpServer.cpp
Labels: bug, documentation, enhancement

#479 [ADD] Documentation for creating a client updater.
  docs/guide/setup/main.xml
  docs/guide/setup/updater/main.xml
  libcomp/doc/Doxyfile.in
  server/channel/doc/Doxyfile.in
  server/lobby/doc/Doxyfile.in
  server/world/doc/Doxyfile.in
  tools/capgrep/doc/Doxyfile.in
  tools/logger/doc/Doxyfile.in
Labels: documentation

#480 Fixing issue with stats unloading while listing characters and preparing for hotfix 2.1.2
  debian/changelog
  libcomp/src/Constants.h
  server/lobby/src/packets/game/CharacterList.cpp
Labels: bug

#484 Null/hack checks and null ref windows backtrace handling
  libcomp/src/Exception.cpp
  server/channel/src/AccountManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/AllocateSkillPoint.cpp
  server/channel/src/packets/game/DemonCrystallize.cpp
  server/channel/src/packets/game/ItemStack.cpp
  server/channel/src/packets/game/PopulateZone.cpp
  server/channel/src/packets/internal/CharacterLogin.cpp
  server/world/src/AccountManager.cpp
  server/world/src/CharacterManager.cpp
Labels: bug

#486 [ADD] REST API to handle a webauth login for the client.
  server/lobby/src/AccountManager.cpp
  server/lobby/src/AccountManager.h
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
  server/lobby/src/main.cpp
Labels: enhancement

#487 LNC compare normalization, tokusei recalc timing and minor fixes
  libcomp/src/Constants.h
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
  server/channel/src/ZoneManager.cpp
  server/world/src/CharacterManager.cpp
  server/world/src/packets/Relay.cpp
Labels: bug

#488 [ADD] Documentation for website setup
  docs/guide/setup/main.xml
  docs/guide/setup/website/main.xml
Labels: documentation

#490 Kodama SP2 and last minute NRA fix
  debian/changelog
  libcomp/src/Constants.h
  server/channel/src/SkillManager.cpp
Labels: bug
