Repository comphack/comp_hack, pull requests merged in 2018-06, with the labels that each got.

#504 Spirit Fusion/Defuse
  contrib/testing/constants.xml
  docs/guide/setup/config/main.xml
  docs/guide/setup/config/world.xml
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/schema/action_grantskills.xml
  libcomp/schema/character.xml
  libcomp/src/Constants.h
  libcomp/src/DefinitionManager.cpp
  libcomp/src/PacketCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/CMakeLists.txt
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/Packets.h
  server/channel/src/packets/game/EquipmentSpiritDefuse.cpp
  server/channel/src/packets/game/EquipmentSpiritFuse.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
  server/channel/src/packets/game/HotbarSave.cpp
  server/channel/src/packets/game/ToggleExpertise.cpp
Labels: enhancement

#520 [MOD] Better version and license information for the server.
  CMakeLists.txt
  cmake/git-version.cmake
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/CMakeLists.txt
  libcomp/schema/serverconfig.xml
  libcomp/src/Config.cpp
  libcomp/src/Config.h
  libcomp/src/Constants.h.in
  libcomp/src/Git.h.in
  server/channel/CMakeLists.txt
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/EventManager.cpp
  server/channel/src/main.cpp
  server/channel/src/packets/game/Chat.cpp
  server/channel/src/packets/game/State.cpp
  server/lobby/src/main.cpp
  server/world/src/main.cpp
Labels: enhancement

#523 Final Lilim functionality
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/CMakeLists.txt
  libcomp/schema/account.xml
  libcomp/schema/character.xml
  libcomp/schema/enemy.xml
  libcomp/schema/qmp_file.xml
  libcomp/schema/serverconfig.xml
  libcomp/schema/spawn.xml
  libcomp/src/DatabaseMariaDB.cpp
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libcomp/src/ErrorCodes.h
  libcomp/src/PacketCodes.h
  server/channel/schema/clientstate.xml
  server/channel/schema/entitystate.xml
  server/channel/schema/loot.xml
  server/channel/schema/zone.xml
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelServer.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/DemonState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/WorldClock.cpp
  server/channel/src/WorldClock.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneGeometry.cpp
  server/channel/src/ZoneGeometry.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/DemonReunion.cpp
  server/channel/src/packets/game/EquipmentModEdit.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/ReviveCharacter.cpp
  server/channel/src/packets/game/Warp.cpp
  server/channel/src/packets/internal/ClanUpdate.cpp
  tools/map/src/MainWindow.cpp
Labels: bug, enhancement

#524 Lilim migration scripts, Sqlite implementation, spawn bug fix
  libcomp/schema/spawn.xml
  libcomp/src/Database.cpp
  libcomp/src/DatabaseMariaDB.cpp
  libcomp/src/DatabaseSQLite3.cpp
  libcomp/src/ScriptEngine.cpp
  libobjgen/src/MetaObjectXmlParser.cpp
  migrations/world/20180701_lilim_accountworlddata.nut
  migrations/world/20180701_lilim_character.nut
  migrations/world/20180701_lilim_demon.nut
  server/channel/src/ChannelServer.cpp
  server/channel/src/WorldClock.cpp
  server/channel/src/WorldClock.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
Labels: bug, enhancement

#528 Skill corrections, convenience features and bug fixes
  libcomp/schema/binarydata/skilldata.xml
  libcomp/src/Constants.h.in
  server/channel/schema/channelconfig.xml
  server/channel/schema/zone.xml
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/ZoneGeometry.cpp
  server/channel/src/ZoneGeometry.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Chat.cpp
  server/channel/src/packets/game/ClanChat.cpp
  server/channel/src/packets/game/FixObjectPosition.cpp
  server/channel/src/packets/game/SendData.cpp
  server/channel/src/packets/game/ShopRepair.cpp
  server/channel/src/packets/game/Tell.cpp
  server/lobby/schema/lobbyconfig.xml
  server/lobby/src/packets/game/CreateCharacter.cpp
  server/world/src/CharacterManager.cpp
  server/world/src/packets/PartyUpdate.cpp
Labels: bug, enhancement

#530 Fixing status effect application type 1 removal
  server/channel/src/SkillManager.cpp
Labels: bug
