Repository comphack/comp_hack, pull requests merged in 2018-02, with the labels that each got.

#393 [ADD] Pre-built binaries for TravisCI builds (Linux).
  .travis.yml
Labels: enhancement

#395 [ADD] Fix to the DH client public parsing.
  libcomp/src/EncryptedConnection.cpp
Labels: bug

#398 Fixing DefinitionManager load issue on case sensitive file systems
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
Labels: bug

#399 Merging pixie into develop as well as minor breakfixes
  .travis.yml
  libcomp/src/Constants.h
  libcomp/src/DefinitionManager.h
  libcomp/src/EncryptedConnection.cpp
  server/channel/src/CharacterManager.cpp
  server/lobby/src/packets/game/CharacterList.cpp
Labels: bug

#402 DB updates, simplified timing, boss boxes and counter crash
  libcomp/schema/account.xml
  libcomp/src/DatabaseMariaDB.cpp
  libcomp/src/DatabaseSQLite3.cpp
  server/channel/schema/clientstate.xml
  server/channel/schema/entitystate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActionManager.h
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ChannelClientConnection.cpp
  server/channel/src/ChannelClientConnection.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelServer.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/ClientState.cpp
  server/channel/src/ClientState.h
  server/channel/src/EventManager.cpp
  server/channel/src/EventManager.h
  server/channel/src/PlasmaState.cpp
  server/channel/src/PlasmaState.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/BazaarMarketInfoSelf.cpp
  server/channel/src/packets/game/BazaarMarketOpen.cpp
  server/channel/src/packets/game/LootBossBox.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/PlasmaItem.cpp
  server/channel/src/packets/game/PlasmaItemData.cpp
  server/channel/src/packets/game/Rotate.cpp
  server/channel/src/packets/game/SendData.cpp
  server/channel/src/packets/game/StopMovement.cpp
  server/channel/src/packets/game/Sync.cpp
  server/channel/src/packets/internal/CharacterLogin.cpp
  server/world/src/CharacterManager.cpp
Labels: bug, enhancement

#403 [FIX] TimerManager and DH Key Exchange
  libcomp/src/EncryptedConnection.cpp
  libcomp/src/TcpConnection.cpp
  libcomp/src/TimerManager.cpp
  libcomp/src/TimerManager.h
Labels: bug

#404 Merge from Pixie, skill and CP item purchasing fixes
  libcomp/src/EncryptedConnection.cpp
  libcomp/src/TcpConnection.cpp
  libcomp/src/TimerManager.cpp
  libcomp/src/TimerManager.h
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/ShopBuy.cpp
Labels: bug

#405 [FIX] Client time was being casted wrong causing 1 second precision.
  server/channel/src/ClientState.cpp
Labels: bug

#408 Finishing off dual/tri-fusion and skill inheritance
  contrib/testing/constants.xml
  libcomp/schema/account.xml
  libcomp/schema/action.xml
  libcomp/schema/action_updatecomp.xml
  libcomp/src/Constants.h
  libcomp/src/PacketCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ChatManager.cpp
  server/channel/src/DemonState.cpp
  server/channel/src/DemonState.h
  server/channel/src/EventManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/FusionManager.h
  server/channel/src/FusionTables.cpp
  server/channel/src/FusionTables.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/packets/game/DemonFusion.cpp
  server/channel/src/packets/game/ShopBuy.cpp
  server/channel/src/packets/game/TriFusionJoin.cpp
Labels: bug, enhancement
