Repository comphack/comp_hack, pull requests merged in 2018-12, with the labels that each got.

#603 Skill interrupt corrections and bug fixes
  libcomp/src/Constants.h.in
  server/channel/src/AIManager.cpp
  server/channel/src/AIState.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/PlasmaState.cpp
  server/channel/src/PlasmaState.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Analyze.cpp
  server/channel/src/packets/game/BazaarItemBuy.cpp
Labels: bug

#604 Fixed Doxygen in the AppVeyor build to use the proper URL.
  .appveyor.yml
Labels: bug

#605 AI adjustments and skill locking
  .appveyor.yml
  .travis.yml
  libcomp/CMakeLists.txt
  libcomp/schema/ailogic.xml
  libcomp/schema/binarydata/aidata.xml
  libcomp/schema/binarydata/devildata.xml
  libcomp/schema/binarydata/skilldata.xml
  libcomp/schema/master.xml
  libcomp/schema/server_zone.xml
  libcomp/schema/spawn.xml
  libcomp/schema/tokusei.xml
  libcomp/src/Constants.h.in
  libcomp/src/ServerDataManager.cpp
  libcomp/src/ServerDataManager.h
  server/channel/schema/aistate.xml
  server/channel/schema/entitystate.xml
  server/channel/src/AICommand.cpp
  server/channel/src/AICommand.h
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/TokuseiManager.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/EquipmentModEdit.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
  server/channel/src/packets/game/ItemRepairMax.cpp
  server/channel/src/packets/game/Synthesize.cpp
  server/channel/src/packets/game/Warp.cpp
Labels: bug, enhancement

#606 Hathor RC2
  CMakeLists.txt
  debian/changelog
  server/channel/schema/entitystate.xml
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterState.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
Labels: bug

#609 [ADD] Message dump when a worker message failed to process.
  CMakeLists.txt
  libcomp/src/Message.h
  libcomp/src/MessageConnectionClosed.cpp
  libcomp/src/MessageConnectionClosed.h
  libcomp/src/MessageEncrypted.cpp
  libcomp/src/MessageEncrypted.h
  libcomp/src/MessageExecute.h
  libcomp/src/MessageInit.cpp
  libcomp/src/MessageInit.h
  libcomp/src/MessagePacket.cpp
  libcomp/src/MessagePacket.h
  libcomp/src/MessagePong.cpp
  libcomp/src/MessagePong.h
  libcomp/src/MessageShutdown.cpp
  libcomp/src/MessageShutdown.h
  libcomp/src/MessageTick.h
  libcomp/src/MessageTimeout.cpp
  libcomp/src/MessageTimeout.h
  libcomp/src/MessageWorldNotification.cpp
  libcomp/src/MessageWorldNotification.h
  libcomp/src/Worker.cpp
Labels: enhancement

#614 [ADD] Component selection to MSI installer.
  CMakeLists.txt
  client/CMakeLists.txt
  contrib/services.wxs
  contrib/wix-background.png
  contrib/wix-banner.png
  server/channel/CMakeLists.txt
  server/lobby/CMakeLists.txt
  server/world/CMakeLists.txt
  tools/bdpatch/CMakeLists.txt
  tools/bgmtool/CMakeLists.txt
  tools/capgrep/CMakeLists.txt
  tools/decrypt/CMakeLists.txt
  tools/encrypt/CMakeLists.txt
  tools/logger/CMakeLists.txt
  tools/logger/src/CMakeLists.txt
  tools/manager/CMakeLists.txt
  tools/map/CMakeLists.txt
  tools/nifcrypt/CMakeLists.txt
  tools/objgen/CMakeLists.txt
  tools/patcher/CMakeLists.txt
  tools/rehash/CMakeLists.txt
  tools/updater/CMakeLists.txt
  tools/updater/src/CMakeLists.txt
Labels: enhancement

#615 [FIX] Update now displays better error messages.
  tools/updater/src/Downloader.cpp
  tools/updater/src/Downloader.h
Labels: enhancement

#616 [ADD] API to get, create and delete promotion codes.
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
Labels: enhancement

#621 [ADD] Shortcut for the Catheral of Content.
  CMakeLists.txt
Labels: enhancement
