Repository comphack/comp_hack, pull requests merged in 2018-11, with the labels that each got.

#566 Skill timing and AI improvements
  .appveyor.yml
  .travis.yml
  contrib/testing/constants.xml
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/schema/action_addremovestatus.xml
  libcomp/schema/action_spawn.xml
  libcomp/schema/binarydata/skilldata.xml
  libcomp/schema/binarydata/statusdata.xml
  libcomp/schema/character.xml
  libcomp/schema/serverconfig.xml
  libcomp/schema/spawn.xml
  libcomp/src/ErrorCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/schema/entitystate.xml
  server/channel/src/AICommand.cpp
  server/channel/src/AICommand.h
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/PlasmaState.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
Labels: enhancement

#568 Slow tick handling, geometry fixes and corrections
  libcomp/src/Constants.h.in
  server/channel/src/AIManager.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelServer.h
  server/channel/src/SkillManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/ZoneGeometry.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/CultureMachineAccess.cpp
  server/channel/src/packets/game/DemonBoxMove.cpp
  server/channel/src/packets/game/DemonForce.cpp
  server/channel/src/packets/game/DiasporaBaseCapture.cpp
  server/channel/src/packets/game/HotbarData.cpp
  server/channel/src/packets/game/ItemPrice.cpp
  server/channel/src/packets/game/PlasmaResult.cpp
  server/channel/src/packets/game/ShopBuy.cpp
  server/channel/src/packets/game/Warp.cpp
  server/world/src/AccountManager.cpp
  server/world/src/CharacterManager.cpp
  server/world/src/CharacterManager.h
  server/world/src/packets/TeamUpdate.cpp
Labels: bug

#569 [ADD] Firewall rules to the MSI installer.
  CMakeLists.txt
  contrib/services.wxs
Labels: enhancement

#570 Status effect expiration bugfix
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterManager.cpp
Labels: bug

#571 Skill adjustments, remaining FIDs, AI restructure and fixes
  .appveyor.yml
  .travis.yml
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/schema/action.xml
  libcomp/schema/binarydata/urafieldtowerdata.xml
  libcomp/schema/enemy.xml
  libcomp/schema/event.xml
  libcomp/schema/serverconfig.xml
  libcomp/schema/tokusei.xml
  libcomp/src/Constants.h.in
  libcomp/src/ErrorCodes.h
  libcomp/src/ServerDataManager.cpp
  server/channel/CMakeLists.txt
  server/channel/schema/aistate.xml
  server/channel/schema/master.xml
  server/channel/schema/zone.xml
  server/channel/src/AICommand.cpp
  server/channel/src/AICommand.h
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/ActionManager.cpp
  server/channel/src/ActionManager.h
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/TokuseiManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/DestinyLotto.cpp
  server/channel/src/packets/game/KeepAlive.cpp
  server/world/src/AccountManager.cpp
  server/world/src/CharacterManager.cpp
Labels: bug, enhancement

#575 Added support for all the BinaryData files used by the channel.
  tools/bdpatch/src/main.cpp
Labels: enhancement

#593 Bug fixes and missed STATUS_REUNION_XP_SAVE effect
  contrib/testing/constants.xml
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  libcomp/src/ServerDataManager.cpp
  server/channel/src/AIManager.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/DemonState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Analyze.cpp
  server/channel/src/packets/game/DemonBoxMove.cpp
  server/channel/src/packets/game/ItemMove.cpp
Labels: bug, enhancement

#596 CLion .idea folder and ignore rule. Fixed various warnings with GCC 7.
  .gitignore
  .idea/comp_hack.iml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  CMakeLists.txt
  libcomp/src/BaseServer.h
  libcomp/src/DefinitionManager.h
  libcomp/src/ServerDataManager.h
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/ObjectInteraction.cpp
  server/channel/src/packets/game/Pivot.cpp
  server/channel/src/packets/game/SpotTriggered.cpp
Labels: enhancement

#597 Bazaars!? Oh snap!
  server/lobby/src/packets/internal/AccountLogin.cpp
  tools/capgrep/CMakeLists.txt
  tools/logger/CMakeLists.txt
  tools/map/CMakeLists.txt
Labels: bug

#598 No hit spawn fix, demon quest adjustments, fusion skill bugs
  server/channel/schema/entitystate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/MatchManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/BazaarMarketOpen.cpp
  server/channel/src/packets/game/Pivot.cpp
  server/channel/src/packets/game/ShopData.cpp
  server/channel/src/packets/game/SkillActivate.cpp
  server/channel/src/packets/game/SkillExecuteInstant.cpp
  server/world/src/AccountManager.cpp
Labels: bug

#599 Add a packet handler to the server.
  .appveyor.yml
  .travis.yml
  contrib/import.html
  docs/guide/setup/config/lobby.xml
  libcomp/src/CString.cpp
  libcomp/src/CString.h
  libcomp/src/PacketCodes.h
  libcomp/src/PersistentObject.cpp
  libcomp/src/PersistentObject.h
  server/channel/CMakeLists.txt
  server/channel/src/AccountManager.cpp
  server/channel/src/AccountManager.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/Packets.h
  server/channel/src/packets/amala/AccountDumpRequest.cpp
  server/channel/src/packets/game/Auth.cpp
  server/lobby/CMakeLists.txt
  server/lobby/schema/lobbyconfig.xml
  server/lobby/src/ImportHandler.cpp
  server/lobby/src/ImportHandler.h
  server/lobby/src/LobbyServer.cpp
  server/lobby/src/LobbyServer.h
  server/lobby/src/main.cpp
Labels: enhancement

#600 Minor fixes to comp_bdpatch and some other things.
  libcomp/src/EncryptedConnection.cpp
  libcomp/src/Packet.cpp
  libcomp/src/ReadOnlyPacket.cpp
  libtester/CMakeLists.txt
  libtester/src/ChannelClient.cpp
  libtester/src/ChannelClient.h
  libtester/src/ChannelClient_HandleAmalaAccountDumpHeader.cpp
  libtester/src/ChannelClient_HandleAmalaAccountDumpPart.cpp
  libtester/src/ChannelClient_HandleAmalaServerVersion.cpp
  server/lobby/src/ImportHandler.cpp
  server/lobby/src/ImportHandler.h
  tests/account_dump.nut
  tools/bdpatch/src/main.cpp
  tools/capgrep/src/MainWindow.cpp
  tools/nifcrypt/src/nifcrypt.cpp
Labels: bug

#601 Crystallization any demon item and misc fixes
  .appveyor.yml
  .travis.yml
  contrib/testing/constants.xml
  libcomp/src/ErrorCodes.h
  libobjgen/res/VariablePersistentReferenceXmlSave.cpp
  server/channel/CMakeLists.txt
  server/channel/src/CharacterManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/world/src/CharacterManager.cpp
  server/world/src/packets/TeamUpdate.cpp
Labels: bug
