Repository comphack/comp_hack, pull requests merged in 2018-07, with the labels that each got.

#531 Time trial results fix, SI_EQUIPPED event type and stage effect rename
  libcomp/schema/action_stageeffect.xml
  server/channel/src/ActionManager.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/ZoneManager.cpp
  tools/capfilter/src/ZoneFilter.cpp
Labels: bug

#532 Add spot ID support to the map viewer
  tools/map/src/MainWindow.cpp
  tools/map/src/MainWindow.h
Labels: enhancement

#547 Lilim SP1 changes
  CMakeLists.txt
  debian/changelog
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/ZoneGeometry.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/DemonForce.cpp
  server/channel/src/packets/game/EquipmentSpiritDefuse.cpp
  server/channel/src/packets/game/EquipmentSpiritFuse.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/SkillActivate.cpp
  server/lobby/src/packets/game/CharacterList.cpp
  server/lobby/src/packets/internal/AccountLogin.cpp
  server/world/src/packets/AccountLogin.cpp
Labels: bug

#549 Lilim SP1 hotfix: SI single slot error
  CMakeLists.txt
  debian/changelog
  server/channel/src/packets/game/EquipmentSpiritFuse.cpp
Labels: bug

#550 [ADD] Build the dream.
  .gitignore
  CMakeLists.txt
  tools/CMakeLists.txt
Labels: question

#551 Web-game support and event delays
  CMakeLists.txt
  contrib/testing/constants.xml
  libcomp/CMakeLists.txt
  libcomp/schema/account.xml
  libcomp/schema/action.xml
  libcomp/schema/action_delay.xml
  libcomp/schema/action_updatepoints.xml
  libcomp/schema/binarydata/npcbarterdata.xml
  libcomp/schema/character.xml
  libcomp/schema/master.xml
  libcomp/schema/server_zone.xml
  libcomp/schema/webgame.xml
  libcomp/src/DataSyncManager.h
  libcomp/src/PacketCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  libcomp/src/ServerDataManager.cpp
  server/channel/CMakeLists.txt
  server/channel/schema/clientstate.xml
  server/channel/schema/zone.xml
  server/channel/src/ActionManager.cpp
  server/channel/src/ActionManager.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelSyncManager.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/ClientState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/EventManager.h
  server/channel/src/Packets.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneInstance.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Barter.cpp
  server/channel/src/packets/game/CasinoCoinTotal.cpp
  server/channel/src/packets/internal/WebGame.cpp
  server/lobby/CMakeLists.txt
  server/lobby/src/AccountManager.cpp
  server/lobby/src/AccountManager.h
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
  server/lobby/src/LobbyServer.cpp
  server/lobby/src/LobbySyncManager.cpp
  server/lobby/src/LobbySyncManager.h
  server/lobby/src/LoginWebHandler.cpp
  server/lobby/src/Packets.h
  server/lobby/src/packets/internal/WebGame.cpp
  server/world/CMakeLists.txt
  server/world/src/AccountManager.cpp
  server/world/src/AccountManager.h
  server/world/src/Packets.h
  server/world/src/WorldServer.cpp
  server/world/src/WorldSyncManager.cpp
  server/world/src/packets/WebGame.cpp
Labels: bug, enhancement
