Repository comphack/comp_hack, pull requests merged in 2018-03, with the labels that each got.

#409 Durability/repair, shop corrections and minor Kodama functionality
  contrib/testing/constants.xml
  libcomp/CMakeLists.txt
  libcomp/schema/binarydata/exchangedata.xml
  libcomp/schema/binarydata/itemdata.xml
  libcomp/schema/binarydata/sstatusdata.xml
  libcomp/schema/binarydata/warppointdata.xml
  libcomp/schema/character.xml
  libcomp/schema/demon.xml
  libcomp/schema/master.xml
  libcomp/schema/server_shop.xml
  libcomp/src/Constants.h
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libcomp/src/PacketCodes.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  libcomp/src/ServerDataManager.cpp
  libcomp/src/ServerDataManager.h
  server/channel/CMakeLists.txt
  server/channel/schema/entitystate.xml
  server/channel/src/AccountManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/FusionManager.cpp
  server/channel/src/Packets.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/TokuseiManager.h
  server/channel/src/packets/game/CompShopList.cpp
  server/channel/src/packets/game/Enchant.cpp
  server/channel/src/packets/game/EquipmentMod.cpp
  server/channel/src/packets/game/EquipmentModEdit.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
  server/channel/src/packets/game/ItemExchange.cpp
  server/channel/src/packets/game/ItemExpand.cpp
  server/channel/src/packets/game/ItemRepairMax.cpp
  server/channel/src/packets/game/PlasmaItemData.cpp
  server/channel/src/packets/game/ShopData.cpp
  server/channel/src/packets/game/ShopRepair.cpp
  server/channel/src/packets/game/SkillForget.cpp
  server/channel/src/packets/game/SyncCharacter.cpp
  server/channel/src/packets/game/Warp.cpp
  tools/capfilter/src/ShopFilter.cpp
Labels: enhancement

#413 Stop channel disconnect on failed client login
  server/channel/src/packets/internal/AccountLogin.cpp
  server/world/src/packets/AccountLogin.cpp
Labels: bug

#412 Fixing enemy spawn delays, party HP upon revival and adding space support in gmand strings
  contrib/testing/constants.xml
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/src/ChatManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/packets/game/ReviveCharacter.cpp
Labels: bug

#414 [ADD] @help for usage of all GMands.
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
Labels: enhancement

#415 [ADD] Some documentation.
  docs/guide/book.xml
  docs/guide/setup/config/common.xml
  docs/guide/setup/config/lobby.xml
  docs/guide/setup/config/main.xml
  docs/guide/setup/config/world.xml
Labels: documentation

#416 [ADD] Testing framework
  CMakeLists.txt
  client/CMakeLists.txt
  client/src/main.cpp
  libcomp/src/ScriptEngine.cpp
  libcomp/src/ScriptEngine.h
  libtester/src/ChannelClient.cpp
  libtester/src/ChannelClient.h
  libtester/src/LobbyClient.cpp
  libtester/src/LobbyClient.h
Labels: enhancement

#418 Minor bug fixes and movement speed update support
  server/channel/src/AIManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/PostItem.cpp
  server/channel/src/packets/game/ShopBuy.cpp
Labels: bug, enhancement

#424 World clock time triggers for spawns and tokusei
  libcomp/schema/action.xml
  libcomp/schema/action_spawn.xml
  libcomp/schema/spawn.xml
  libcomp/schema/tokusei.xml
  libcomp/src/Constants.h
  libcomp/src/TimerManager.h
  server/channel/CMakeLists.txt
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelServer.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/EventManager.cpp
  server/channel/src/ManagerConnection.cpp
  server/channel/src/ManagerConnection.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/TokuseiManager.h
  server/channel/src/WorldClock.cpp
  server/channel/src/WorldClock.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/SendData.cpp
  server/channel/src/packets/game/WorldTime.cpp
Labels: bug, enhancement

#425 [ADD] Updated documentation for the configuration XML.
  contrib/sources.sh
  docs/guide/setup/config/channel.xml
  docs/guide/setup/config/common.xml
  docs/guide/setup/config/database.xml
  docs/guide/setup/config/lobby.xml
  docs/guide/setup/config/main.xml
  docs/guide/setup/config/mariadb.xml
  docs/guide/setup/config/sqlite3.xml
  docs/guide/setup/config/world.xml
Labels: documentation

#426 [ADD] New server test code.
  .travis.yml
  client/src/main.cpp
  libcomp/src/BaseServer.cpp
  libtester/CMakeLists.txt
  libtester/src/ChannelClient.cpp
  libtester/src/ChannelClient.h
  libtester/src/ChannelClient_HandleDemonBoxData.cpp
  libtester/src/ChannelClient_HandleZoneChange.cpp
  libtester/src/LobbyClient.cpp
  libtester/src/LobbyClient.h
  libtester/src/ServerTest.h
  libtester/src/TestClient.cpp
  libtester/src/TestClient.h
  server/lobby/src/AccountManager.cpp
  tests/000.000_status_effect_db_corruption.nut
  tests/002.005_free_character_ticket.nut
  tests/run.py
  tests/test.nut
Labels: enhancement

#428 Allowing selective client-less events
  server/channel/src/ActionManager.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/EventManager.h
  server/channel/src/ZoneManager.cpp
Labels: enhancement

#430 Remaining functional parts of search lists and several bug fixes
  libcomp/schema/item.xml
  libcomp/src/Constants.h
  libcomp/src/DataSyncManager.cpp
  server/channel/src/AccountManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ClientState.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/ClanForm.cpp
  server/channel/src/packets/game/FixObjectPosition.cpp
  server/channel/src/packets/game/ItemPrice.cpp
  server/channel/src/packets/game/PlasmaEnd.cpp
  server/channel/src/packets/game/SearchEntryData.cpp
  server/channel/src/packets/game/SearchEntryRegister.cpp
  server/channel/src/packets/game/SearchEntrySelf.cpp
  server/channel/src/packets/game/TriFusionJoin.cpp
  server/channel/src/packets/game/Warp.cpp
  server/channel/src/packets/internal/ClanUpdate.cpp
  server/world/src/AccountManager.cpp
  server/world/src/WorldSyncManager.cpp
  server/world/src/WorldSyncManager.h
Labels: bug, enhancement

#433 Fixing traesto issue and package name
  CMakeLists.txt
  debian/changelog
  server/channel/src/SkillManager.cpp
Labels: bug

#439 Fixing recalc crash, defeatActions issue and handling skill stats more accurately
  libcomp/src/Constants.h
  libcomp/src/DataSyncManager.cpp
  libcomp/src/Randomizer.cpp
  libcomp/src/Randomizer.h
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ChatManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/AllocateSkillPoint.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
  server/channel/src/packets/game/SkillForget.cpp
  server/channel/src/packets/game/UpdateDemonSkill.cpp
  server/channel/src/packets/internal/AccountLogin.cpp
  server/channel/src/packets/internal/ClanUpdate.cpp
  server/world/src/packets/AccountLogin.cpp
Labels: bug

#446 More tokusei and some bug fixes
  contrib/testing/constants.xml
  contrib/testing/newcharacter.xml
  contrib/winconfig/newcharacter.xml
  libcomp/schema/character.xml
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libcomp/src/ServerConstants.cpp
  libcomp/src/ServerConstants.h
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
  server/lobby/src/AccountManager.cpp
  server/lobby/src/AccountManager.h
  server/lobby/src/packets/game/CharacterList.cpp
  server/lobby/src/packets/game/CreateCharacter.cpp
  server/lobby/src/packets/internal/AccountLogin.cpp
Labels: bug

#447 Various bug fixes
  libcomp/schema/demon.xml
  libcomp/src/ServerDataManager.cpp
  server/channel/src/AIManager.cpp
  server/channel/src/AccountManager.cpp
  server/channel/src/packets/game/Barter.cpp
  server/channel/src/packets/game/ExpertiseDown.cpp
Labels: bug

#449 Bug fixes
  libcomp/src/TimerManager.cpp
  libcomp/src/TimerManager.h
  libobjgen/src/MetaVariable.cpp
  server/channel/src/packets/game/ShopSell.cpp
  server/lobby/src/LoginWebHandler.cpp
Labels: bug, enhancement

#450 [ADD] Ability to spread a spawn group across multiple spots.
  libcomp/schema/spawn.xml
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
Labels: enhancement

#451 Tokusei leftovers and world shared configs
  libcomp/CMakeLists.txt
  libcomp/schema/serverconfig.xml
  libcomp/schema/tokusei.xml
  libcomp/src/PacketCodes.h
  server/channel/CMakeLists.txt
  server/channel/schema/channelconfig.xml
  server/channel/schema/clientstate.xml
  server/channel/schema/entitystate.xml
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/ChannelServer.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/ClientState.cpp
  server/channel/src/ClientState.h
  server/channel/src/Packets.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/TokuseiManager.h
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/FixObjectPosition.cpp
  server/channel/src/packets/game/PAttributeDeadline.cpp
  server/channel/src/packets/game/ReviveCharacter.cpp
  server/channel/src/packets/game/SendData.cpp
  server/channel/src/packets/game/State.cpp
  server/channel/src/packets/internal/SetWorldInfo.cpp
  server/world/schema/worldconfig.xml
  server/world/src/packets/GetWorldInfo.cpp
Labels: bug, enhancement

#452 Switching to 64-bit RelWithDebInfo for appveyor and adding worker exception backtraces
  .appveyor.yml
  .travis.yml
  libcomp/src/Worker.cpp
Labels: bug

#453 [ADD] @flag GMand for printing and changing zone and instance flags.
  server/channel/src/ChatManager.cpp
  server/channel/src/ChatManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneInstance.cpp
  server/channel/src/ZoneInstance.h
Labels: enhancement

#454 [MOD] Faster builds on the travis build server.
  .travis.yml
  CMakeLists.txt
  cmake/cotire.cmake
  libcomp/CMakeLists.txt
  libcomp/schema/character.xml
  server/channel/CMakeLists.txt
  server/channel/src/EventManager.cpp
  server/channel/src/packets/game/SpotTriggered.cpp
  server/lobby/CMakeLists.txt
  server/lobby/src/packets/game/Auth.cpp
  server/world/CMakeLists.txt
Labels: enhancement

#455 Crash fixes
  libcomp/src/ManagerPacket.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/packets/game/ObjectInteraction.cpp
  server/channel/src/packets/game/SpotTriggered.cpp
  server/channel/src/packets/game/TradeAccept.cpp
  server/world/src/CharacterManager.cpp
  server/world/src/packets/Relay.cpp
Labels: bug

#457 Proper character deletion, Windows PDBs, appearance alteration and bugs
  libcomp/schema/account.xml
  libcomp/schema/binarydata/itemdata.xml
  libcomp/schema/demon.xml
  libcomp/src/DataSyncManager.cpp
  libcomp/src/DataSyncManager.h
  libcomp/src/DefinitionManager.cpp
  libcomp/src/PacketCodes.h
  libobjgen/res/VariableEnumLoad.cpp
  libobjgen/src/MetaVariableEnum.cpp
  server/channel/CMakeLists.txt
  server/channel/src/ChannelServer.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/Packets.h
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Analyze.cpp
  server/channel/src/packets/game/AppearanceAlter.cpp
  server/channel/src/packets/game/ItemStack.cpp
  server/lobby/CMakeLists.txt
  server/lobby/src/AccountManager.cpp
  server/lobby/src/LobbySyncManager.cpp
  server/lobby/src/LobbySyncManager.h
  server/lobby/src/packets/game/CreateCharacter.cpp
  server/lobby/src/packets/game/DeleteCharacter.cpp
  server/world/CMakeLists.txt
  server/world/src/AccountManager.cpp
  server/world/src/AccountManager.h
  server/world/src/CharacterManager.cpp
  server/world/src/CharacterManager.h
  server/world/src/WorldSyncManager.cpp
  server/world/src/WorldSyncManager.h
  server/world/src/packets/GetWorldInfo.cpp
Labels: bug, enhancement

#459 Equipped VA issues
  libcomp/schema/character.xml
  libcomp/src/Constants.h
  server/channel/src/CharacterManager.cpp
  server/lobby/src/packets/game/CharacterList.cpp
Labels: bug

#460 Fixing RecalcDisabledSkills for chain expertise
  libcomp/src/Constants.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/FusionManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
Labels: bug
