Repository comphack/comp_hack, pull requests merged in 2019-06, with the labels that each got.

#963 Fixing the CDevilEquipmentExclusiveData type in bdpatch
  tools/bdpatch/src/main.cpp
Labels: bug

#964 Prevent destiny drops from combining and Eoh (Unstable) version bump
  CMakeLists.txt
  server/channel/src/SkillManager.cpp
Labels: bug

#972 Fix service dependencies on reduced Windows install
  cmake/deps/zlib.cmake
  contrib/services.wxs
Labels: bug

#985 Additional webgame bindings for RNG, timing and more PersistentObject access
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
Labels: bug, enhancement

#986 Explicit zero item costs should still inherently apply and tokusei lower limits
  server/channel/src/SkillManager.cpp
Labels: bug

#987 Spirit fusion great success modifiers adjust bonuses too
  server/channel/src/packets/game/EquipmentSpiritFuse.cpp
Labels: bug

#991 Fixing Zone::SetFlagState script binding
  server/channel/src/Zone.cpp
Labels: bug

#993 Implementing proper clench behavior for extra damage
  server/channel/src/SkillManager.cpp
Labels: bug

#994 Fixing incorrect (rarely requested) SyncCharacter response format
  server/channel/src/packets/game/SyncCharacter.cpp
Labels: bug

#1000 UltimateBattle and Pentalpha implementation changes
  server/channel/schema/zone.xml
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ChannelSyncManager.cpp
  server/channel/src/MatchManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/world/src/WorldServer.cpp
  server/world/src/WorldSyncManager.cpp
Labels: bug, enhancement

#1005 SkipInvalid events and cathedral improvements/implementations
  server/channel/src/EventManager.cpp
  tools/cathedral/src/DropSetWindow.cpp
  tools/cathedral/src/EventBaseUI.cpp
  tools/cathedral/src/EventBaseUI.h
  tools/cathedral/src/EventChoiceUI.cpp
  tools/cathedral/src/EventUI.cpp
  tools/cathedral/src/EventWindow.cpp
  tools/cathedral/ui/DropSetProperties.ui
  tools/cathedral/ui/Event.ui
  tools/cathedral/ui/EventBase.ui
  tools/cathedral/ui/ZoneTrigger.ui
Labels: enhancement
