Repository comphack/comp_hack, pull requests merged in 2019-02, with the labels that each got.

#862 Skill effect bug, search entry dupes and Cathedral settings
  libcomp/src/Constants.h.in
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/SearchEntryRegister.cpp
  tools/cathedral/CMakeLists.txt
  tools/cathedral/src/MainWindow.cpp
  tools/cathedral/src/MainWindow.h
  tools/cathedral/src/SettingsWindow.cpp
  tools/cathedral/src/SettingsWindow.h
  tools/cathedral/ui/MainWindow.ui
  tools/cathedral/ui/SettingsWindow.ui
Labels: bug, enhancement

#863 AI nice to haves and some bugs
  server/channel/schema/aistate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/FusionManager.cpp
  server/channel/src/FusionTables.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/lobby/src/packets/game/CharacterList.cpp
Labels: bug, enhancement

#864 [FIX] Include the username in all API requests and store the session by username.
  contrib/webroot/accountmanager/index.html
  server/lobby/src/ApiHandler.cpp
Labels: bug

#865 [ADD] Documentaton for building the project from source on Windows.
  docs/guide/book.xml
  docs/guide/content/main.xml
  docs/guide/content/zone.xml
  docs/guide/setup/config/common.xml
  docs/guide/setup/main.xml
  docs/guide/setup/source/main.xml
  docs/guide/static/clone1.png
  docs/guide/static/clone2.png
  docs/guide/static/clone3.png
  docs/guide/static/clone4.png
  docs/guide/static/cmake.png
  docs/guide/static/docbook.css
  docs/guide/static/fork.png
  docs/guide/static/project_generation.png
  docs/guide/static/qt.png
  docs/guide/static/vs2015cpp.png
  docs/guide/static/vssolution.png
Labels: documentation

#866 Converting web game "start" to use normal response structure
  server/lobby/src/ApiHandler.cpp
Labels: bug

#868 [FIX] Session username conflicted with the target username for API requests.
  contrib/webroot/accountmanager/index.html
  server/lobby/src/ApiHandler.cpp
Labels: bug

#876 Demon acquired skill 0 ID fix
  migrations/world/20190220_hathor_demonskills.nut
  server/channel/src/CharacterManager.cpp
  server/lobby/src/packets/internal/AccountLogout.cpp
  tools/cathedral/src/EventConditionUI.cpp
  tools/cathedral/src/MainWindow.cpp
Labels: bug, code
