Repository comphack/comp_hack, pull requests merged in 2019-01, with the labels that each got.

#622 Adding all translatable text objects to bdpatch, implementing unused barter types
  .appveyor.yml
  .travis.yml
  libcomp/CMakeLists.txt
  libcomp/schema/action_zoneinstance.xml
  libcomp/schema/binarydata/bazaarclerknpcdata.xml
  libcomp/schema/binarydata/cchanceitemdata.xml
  libcomp/schema/binarydata/cculturedata.xml
  libcomp/schema/binarydata/cdevilbookbonusdata.xml
  libcomp/schema/binarydata/cdevilbookbonusmitamadata.xml
  libcomp/schema/binarydata/cdevildungeondata.xml
  libcomp/schema/binarydata/cdevilequipmentexclusivedata.xml
  libcomp/schema/binarydata/cequipmodeldata.xml
  libcomp/schema/binarydata/cguardianassistdata.xml
  libcomp/schema/binarydata/chelpdata.xml
  libcomp/schema/binarydata/chouraidata.xml
  libcomp/schema/binarydata/ckeyitemdata.xml
  libcomp/schema/binarydata/cloadingcommercialdata.xml
  libcomp/schema/binarydata/cmapdata.xml
  libcomp/schema/binarydata/cmodifiedeffectdata.xml
  libcomp/schema/binarydata/cskilldata.xml
  libcomp/schema/binarydata/cspecialskilleffectdata.xml
  libcomp/schema/binarydata/cstatusdata.xml
  libcomp/schema/binarydata/ctimeattackdata.xml
  libcomp/schema/binarydata/ctitledata.xml
  libcomp/schema/binarydata/ctransformedmodeldata.xml
  libcomp/schema/binarydata/cvaluablesdata.xml
  libcomp/schema/binarydata/czonerelationdata.xml
  libcomp/schema/binarydata/devillvupratedata.xml
  libcomp/schema/binarydata/dynamicmapdata.xml
  libcomp/schema/binarydata/enchantdata.xml
  libcomp/schema/binarydata/exchangedata.xml
  libcomp/schema/binarydata/gvgtrophydata.xml
  libcomp/schema/binarydata/missiondata.xml
  libcomp/schema/binarydata/mitamadata.xml
  libcomp/schema/binarydata/modificationdata.xml
  libcomp/schema/binarydata/npcbarterdata.xml
  libcomp/schema/binarydata/questbonusdata.xml
  libcomp/schema/binarydata/questdata.xml
  libcomp/schema/binarydata/reporttypedata.xml
  libcomp/schema/binarydata/tankdata.xml
  libcomp/schema/binarydata/timelimitdata.xml
  libcomp/schema/binarydata/uiinfodata.xml
  libcomp/schema/binarydata/warppointdata.xml
  libcomp/schema/master.xml
  libcomp/src/DefinitionManager.cpp
  libcomp/src/DefinitionManager.h
  libobjgen/res/VariableIndirectReferenceXmlSave.cpp
  libobjgen/res/VariablePersistentReferenceXmlSave.cpp
  libobjgen/res/VariableReferenceXmlLoad.cpp
  libobjgen/res/VariableReferenceXmlSave.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/packets/game/Barter.cpp
  server/channel/src/packets/game/MaterialInsert.cpp
  tools/bdpatch/src/main.cpp
  tools/cathedral/src/ActionCreateLootUI.cpp
  tools/cathedral/src/ActionZoneInstanceUI.cpp
  tools/cathedral/src/DynamicList.cpp
  tools/cathedral/src/EventWindow.cpp
  tools/cathedral/ui/ActionZoneInstance.ui
Labels: bug, enhancement

#623 [ADD] Threading to QMP loading.
  server/channel/CMakeLists.txt
  server/channel/src/ZoneGeometryLoader.cpp
  server/channel/src/ZoneGeometryLoader.h
  server/channel/src/ZoneManager.cpp
Labels: enhancement

#638 Cathedral of Content search controls
  tools/cathedral/CMakeLists.txt
  tools/cathedral/src/ActionList.cpp
  tools/cathedral/src/ActionList.h
  tools/cathedral/src/DropSetWindow.cpp
  tools/cathedral/src/DropSetWindow.h
  tools/cathedral/src/EventWindow.cpp
  tools/cathedral/src/EventWindow.h
  tools/cathedral/src/FindRefWindow.cpp
  tools/cathedral/src/FindRefWindow.h
  tools/cathedral/src/MainWindow.cpp
  tools/cathedral/src/ObjectSelectorList.cpp
  tools/cathedral/src/ObjectSelectorList.h
  tools/cathedral/src/ObjectSelectorWindow.cpp
  tools/cathedral/src/ObjectSelectorWindow.h
  tools/cathedral/src/ZoneWindow.cpp
  tools/cathedral/src/ZoneWindow.h
  tools/cathedral/ui/DropSetWindow.ui
  tools/cathedral/ui/EventWindow.ui
  tools/cathedral/ui/FindEventAction.ui
  tools/cathedral/ui/FindRefWindow.ui
  tools/cathedral/ui/ObjectSelectorWindow.ui
Labels: enhancement

#639 Diaspora quake and bug fixes
  contrib/testing/constants.xml
  server/channel/schema/clientstate.xml
  server/channel/schema/zone.xml
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/BazaarState.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/ManagerConnection.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/BazaarMarketInfo.cpp
  server/channel/src/packets/game/ItemMix.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/SendData.cpp
  server/lobby/src/packets/internal/AccountLogin.cpp
  server/world/src/AccountManager.cpp
  server/world/src/WorldSyncManager.cpp
  server/world/src/WorldSyncManager.h
  server/world/src/packets/AccountLogout.cpp
Labels: bug, enhancement

#641 More accurate tokusei conditions and status effect cancellations
  .appveyor.yml
  .travis.yml
  libcomp/schema/action_createloot.xml
  libcomp/schema/binarydata/devildata.xml
  libcomp/schema/event.xml
  libcomp/schema/tokusei.xml
  libobjgen/res/VariableMapAccessDeclarations.cpp
  libobjgen/res/VariableMapAccessFunctions.cpp
  libobjgen/res/VariableMapAccessScriptBindings.cpp
  libobjgen/res/VariableSetAccessDeclarations.cpp
  libobjgen/res/VariableSetAccessFunctions.cpp
  libobjgen/res/VariableSetAccessScriptBindings.cpp
  server/channel/schema/clientstate.xml
  server/channel/schema/entitystate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/AccountManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/DemonState.cpp
  server/channel/src/DemonState.h
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/ZoneInstance.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/SendData.cpp
  server/channel/src/packets/game/State.cpp
  server/channel/src/packets/internal/AccountLogin.cpp
  tools/cathedral/src/ActionCreateLootUI.cpp
  tools/cathedral/src/EventConditionUI.cpp
  tools/cathedral/ui/ActionCreateLoot.ui
Labels: bug

#642 Better collision checking and bug fixes
  .appveyor.yml
  .travis.yml
  libcomp/schema/tokusei.xml
  libcomp/src/Constants.h.in
  server/channel/schema/aistate.xml
  server/channel/schema/clientstate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/AIState.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/AllocateSkillPoint.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/ObjectInteraction.cpp
  server/channel/src/packets/game/Pivot.cpp
  server/channel/src/packets/game/StopMovement.cpp
  server/world/src/packets/AccountLogout.cpp
Labels: bug

#643 [FIX] Issue with item stacks not working properly.
  server/channel/src/AccountManager.cpp
  server/channel/src/packets/game/ItemStack.cpp
Labels: bug

#644 Geometry fixes and web game scripts
  libcomp/src/ServerDataManager.cpp
  libcomp/src/ServerDataManager.h
  server/channel/src/AIManager.cpp
  server/channel/src/AccountManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneGeometryLoader.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
Labels: bug

#859 Various fixes
  .appveyor.yml
  .travis.yml
  docs/guide/setup/config/worldsharedconfig.xml
  libcomp/schema/binarydata/enchantdata.xml
  libcomp/schema/serverconfig.xml
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/TokuseiManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/Enchant.cpp
  server/channel/src/packets/game/Move.cpp
  server/channel/src/packets/game/ObjectInteraction.cpp
  server/channel/src/packets/game/Pivot.cpp
  server/channel/src/packets/game/StopMovement.cpp
Labels: bug
