Repository comphack/comp_hack, pull requests merged in 2019-04, with the labels that each got.

#886 Exploit patching and bug fixes
  server/channel/src/AIManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/EquipmentSpiritDefuse.cpp
  server/channel/src/packets/game/LootItem.cpp
  server/channel/src/packets/game/LootTreasureBox.cpp
  server/channel/src/packets/game/ObjectInteraction.cpp
  server/channel/src/packets/game/PlasmaItemData.cpp
  server/channel/src/packets/game/TradeAddItem.cpp
  server/channel/src/packets/game/TriFusionJoin.cpp
  server/lobby/src/AccountManager.cpp
Labels: bug

#895 [FIX] Issue where tell bounceback would cause a string encoding error.
  server/channel/src/packets/internal/Relay.cpp
Labels: bug

#898 Diaspora and Mission instance bug fixes
  contrib/testing/constants.xml
  server/channel/src/Zone.cpp
  server/channel/src/ZoneManager.cpp
Labels: bug, code

#899 Knockback time is constant and detached from hitstun
  server/channel/src/SkillManager.cpp
Labels: bug, code

#901 Fixing refresh/move for events not already saved
  tools/cathedral/src/EventWindow.cpp
Labels: bug, code

#904 Support for more obscure AI/GM skills
  server/channel/src/SkillManager.cpp
Labels: bug, code

#906 [ADD] Links that should open in a new window or tab now open in the external browser.
  tools/updater/CMakeLists.txt
  tools/updater/src/UpdaterWebEngineView.cpp
  tools/updater/src/UpdaterWebEngineView.h
  tools/updater/trans/updater_en_US.ts
  tools/updater/trans/updater_ja_JP.ts
  tools/updater/trans/updater_ru_RU.ts
  tools/updater/ui/Updater.ui
Labels: enhancement
