Repository comphack/comp_hack, pull requests merged in 2019-11, with the labels that each got.

#1092 Fix Windows TravisCI build
  ci/linux-build.sh
  ci/linux-channel.sh
  ci/linux-libcomp.sh
  ci/qt-installer-windows.qs
  ci/report-progress.sh
  ci/travis-install-qt-windows.sh
  ci/windows-build.sh
  ci/windows-channel.sh
  ci/windows-libcomp.sh
  ci/windows-updater.sh
Labels: bug, code

#1088 Enabling event XP loss, fixing issues with AoE reflect and app logic type 1 status effects
  server/channel/src/ActionManager.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/ChatManager.cpp
  server/channel/src/MatchManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/DemonQuestEnd.cpp
  tools/cathedral/src/EventWindow.cpp
  tools/cathedral/src/EventWindow.h
  tools/cathedral/ui/ActionGrantXP.ui
  tools/cathedral/ui/EventWindow.ui
Labels: bug, enhancement

#1093 Bug fixes for Uruz
  server/channel/schema/entitystate.xml
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/CharacterState.cpp
  server/channel/src/ChatManager.cpp
  server/channel/src/DemonState.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/TokuseiManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/BazaarItemBuy.cpp
  server/channel/src/packets/game/ItemMix.cpp
  server/channel/src/packets/game/SearchEntryData.cpp
  server/channel/src/packets/game/SearchEntryRegister.cpp
  server/channel/src/packets/game/SearchList.cpp
Labels: bug

#1094 ItemMix great success crash fix redux
  server/channel/src/packets/game/ItemMix.cpp
Labels: bug

#1097 [FIX] Linker error on old versions of Ubuntu (Xenial).
  server/channel/src/MatchManager.cpp
Labels: bug

#1098 [FIX] Don't exclude ImagineUpdate.dat from rehash (fixes #1091)
  tools/rehash/src/main.cpp
Labels: bug, code
