Repository comphack/comp_hack, pull requests merged in 2020-01, with the labels that each got.

#1111 DIE ZOMBIE
  server/world/src/AccountManager.cpp
  server/world/src/WorldSyncManager.cpp
Labels: bug

#1113 [ADD] Check if we want to recheck before doing a recheck.
  tools/updater/src/Updater.cpp
Labels: code, feature request

#1114 v4.7.0 Laguz
  CMakeLists.txt
  README.md
  debian/changelog
Labels: code

#1115 Switch back to unstable (Ansuz)
  CMakeLists.txt
Labels: code

#1118 Fixing bugs in new Laguz functionality
  server/channel/src/AIManager.cpp
  server/channel/src/CharacterManager.cpp
Labels: bug

#1132 Updating multiclient logic to lower counts properly
  server/lobby/src/AccountManager.cpp
  server/lobby/src/AccountManager.h
Labels: bug

#1134 v4.8.0 Ansuz
  CMakeLists.txt
  README.md
  debian/changelog
Labels: code
