Repository comphack/comp_hack, pull requests merged in 2020-06, with the labels that each got.

#1219 Fixing time based tokusei condition option groups
  server/channel/src/TokuseiManager.cpp
  server/channel/src/packets/game/BazaarItemAdd.cpp
  server/channel/src/packets/game/DemonForce.cpp
Labels: bug

#1220 Cast/CD/heal rate corrections, talk skill and demon quest adjustments
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/SkillManager.cpp
Labels: bug

#1221 Proper no expiration entity status checks, minor talk fix
  server/channel/src/AIManager.cpp
  server/channel/src/CharacterState.cpp
  server/channel/src/SkillManager.cpp
Labels: bug

#1223 Tarot/soul ability should be taken from basic item effect
  server/channel/src/CharacterManager.cpp
Labels: bug

#1224 v4.12.1 Wyrd Hotfix 1
  CMakeLists.txt
  README.md
  debian/changelog
Labels: code

#1225 [ADD] New guide that uses reStructuredText.
  .readthedocs.yml
  CMakeLists.txt
  README.md
  ci/github-linux.sh
  ci/linux-build.sh
  contrib/pages/index.html
  docs/CMakeLists.txt
  docs/guide/.gitignore
  docs/guide/CMakeLists.txt
  docs/guide/Makefile
  docs/guide/_static/bgm_audacity.png
  docs/guide/_static/bgm_miles.png
  docs/guide/_static/clone1.png
  docs/guide/_static/clone2.png
  docs/guide/_static/clone3.png
  docs/guide/_static/clone4.png
  docs/guide/_static/cmake.png
  docs/guide/_static/docbook.css
  docs/guide/_static/fork.png
  docs/guide/_static/project_generation.png
  docs/guide/_static/qt.png
  docs/guide/_static/vs2015cpp.png
  docs/guide/_static/vssolution.png
  docs/guide/arch/main.xml
  docs/guide/book.xml
  docs/guide/chapters/config.rst
  docs/guide/chapters/content.rst
  docs/guide/chapters/hacking.rst
  docs/guide/chapters/intro.rst
  docs/guide/chapters/setup.rst
  docs/guide/conf.py
  docs/guide/config.xsl
  docs/guide/content/bgm.xml
  docs/guide/content/main.xml
  docs/guide/content/zone.xml
  docs/guide/index.rst
  docs/guide/intro/main.xml
  docs/guide/logo.svg
  docs/guide/make.bat
  docs/guide/setup/config/channel.xml
  docs/guide/setup/config/common.xml
  docs/guide/setup/config/database.xml
  docs/guide/setup/config/lobby.xml
  docs/guide/setup/config/main.xml
  docs/guide/setup/config/mariadb.xml
  docs/guide/setup/config/sqlite3.xml
  docs/guide/setup/config/world.xml
  docs/guide/setup/config/worldsharedconfig.xml
  docs/guide/setup/linux/main.xml
  docs/guide/setup/main.xml
  docs/guide/setup/require/main.xml
  docs/guide/setup/source/main.xml
  docs/guide/setup/updater/main.xml
  docs/guide/setup/website/main.xml
Labels: documentation
