Repository comphack/comp_hack, pull requests merged in 2020-04, with the labels that each got.

#1169 Fixing race condition with ActiveEntityState::ExpireStatusTimes and some playtest issues
  server/channel/src/AIManager.cpp
  server/channel/src/ActionManager.cpp
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
Labels: bug

#1178 Implementing more item and skill restriction checks
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/packets/game/BazaarItemAdd.cpp
  server/channel/src/packets/game/DemonEquip.cpp
  server/channel/src/packets/game/EquipmentSpiritFuse.cpp
  server/channel/src/packets/game/ItemDrop.cpp
  server/channel/src/packets/game/ItemMove.cpp
  server/channel/src/packets/game/ShopRepair.cpp
  server/channel/src/packets/game/ShopSell.cpp
  server/channel/src/packets/game/SkillActivate.cpp
  server/channel/src/packets/game/TradeAddItem.cpp
Labels: bug

#1186 Skill bugs and item flag fixes
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/packets/game/EntrustRewardUpdate.cpp
  server/channel/src/packets/game/SkillActivate.cpp
  server/channel/src/packets/game/SkillExecuteInstant.cpp
  server/channel/src/packets/game/TriFusionRewardUpdate.cpp
Labels: bug

#1192 Pentalpha fixes and implementing libcomp updates
  client/src/main.cpp
  docs/guide/setup/config/worldsharedconfig.xml
  server/channel/src/AccountManager.cpp
  server/channel/src/MatchManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/main.cpp
  server/channel/src/packets/game/BazaarMarketOpen.cpp
  server/channel/src/packets/game/BazaarState.cpp
  server/channel/src/packets/game/PentalphaData.cpp
  server/lobby/src/main.cpp
  server/lobby/src/packets/game/CharacterList.cpp
  server/world/src/WorldSyncManager.cpp
  server/world/src/main.cpp
  tools/bdpatch/src/main.cpp
  tools/cathedral/src/MainWindow.cpp
Labels: bug, enhancement

#1193 Fixing double NRA bug, instance disconnect relog location and clan loading issue
  server/channel/src/ChatManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/packets/game/TriFusionJoin.cpp
  server/channel/src/packets/game/VABoxAdd.cpp
  server/world/src/CharacterManager.cpp
Labels: bug

#1194 v4.11.0 Sigel
  CMakeLists.txt
  README.md
  debian/changelog
Labels: code
