Repository comphack/comp_hack, pull requests merged in 2020-11, with the labels that each got.

#1288 [ADD] Initial GitHub CI actions
  .github/workflows/ci.yml
  .travis.yml
  ci/checksums/external-0.1.1-clang.tar.bz2.sha1
  ci/checksums/external-0.1.1-gcc5.tar.bz2.sha1
  ci/checksums/external-0.1.1-win32.zip.sha1
  ci/checksums/external-0.1.1-win64.zip.sha1
  ci/checksums/external-linux-clang.tar.bz2.sha1
  ci/checksums/external-linux-gcc.tar.bz2.sha1
  ci/checksums/external-win32-msvc2017.zip.sha1
  ci/checksums/external-win64-msvc2017.zip.sha1
  ci/clang-format.sh
  ci/dropbox-deployment-1.0.0.gem
  ci/github-linux.sh
  ci/github-win32.ps1
  ci/github-win64.ps1
  ci/global.sh
  ci/linux-before_install.sh
  ci/linux-build.sh
  ci/linux-channel.sh
  ci/linux-libcomp.sh
  ci/linux-warmcache.sh
  ci/windows-build.ps1
  ci/windows-build.sh
  ci/windows-channel.sh
  ci/windows-libcomp.sh
  ci/windows-updater-build.ps1
  ci/windows-updater.sh
  ci/windows-warmcache.sh
  server/channel/src/ZoneGeometry.cpp
  server/channel/src/ZoneGeometry.h
  server/channel/src/ZoneManager.cpp
  server/world/src/CharacterManager.cpp
Labels: enhancement

#1286 [ADD] Settings for the client DLL to the updater.
  tools/updater/CMakeLists.txt
  tools/updater/src/ClientPatches.cpp
  tools/updater/src/ClientPatches.h
  tools/updater/src/Options.cpp
  tools/updater/src/Options.h
  tools/updater/trans/updater_en_US.ts
  tools/updater/trans/updater_ja_JP.ts
  tools/updater/trans/updater_ru_RU.ts
  tools/updater/ui/Options.ui
Labels: code, enhancement

#1289 [MOD] Make the other builds wait for clang format.
  .github/workflows/ci.yml
Labels: enhancement

#1290 Update interactions of Status Effects and HP/MP Regeneration
  server/channel/src/ActiveEntityState.cpp
Labels: bug, code

#1273 Knockback values are updated even if knockback is nullified
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1295 Negotiation friendship fix
  server/channel/src/ActionManager.cpp
  server/channel/src/packets/game/LootItem.cpp
Labels: bug, code

#1302 [MOD] Add option to skip installing tools in the CI.
  .github/workflows/ci.yml
  CMakeLists.txt
  ci/linux-build.sh
  ci/windows-build.ps1
  ci/windows-updater-build.ps1
Labels: code, enhancement
