Repository comphack/comp_hack, pull requests merged in 2020-10, with the labels that each got.

#1262 [FIX] Crash on zone change when status effect was not properly removed.
  server/channel/src/ActiveEntityState.cpp
Labels: bug, code

#1264 [ADD] Support to build both 32-bit and 64-bit on windows with pre-built binaries.
  .travis.yml
  CMakeLists.txt
  ci/linux-warmcache.sh
  ci/windows-warmcache.sh
  cmake/deps/asio.cmake
  cmake/deps/civet.cmake
  cmake/deps/googletest.cmake
  cmake/deps/gsl.cmake
  cmake/deps/jsonbox.cmake
  cmake/deps/mariadb.cmake
  cmake/deps/mbedtls.cmake
  cmake/deps/openssl.cmake
  cmake/deps/physfs.cmake
  cmake/deps/squirrel3.cmake
  cmake/deps/tinyxml2.cmake
  cmake/deps/ttvfs.cmake
  cmake/deps/zlib.cmake
  vsbuild_x64.bat
  vsbuild_x86.bat
Labels: code, enhancement

#1265 [ADD] Better updater logging.
  server/channel/src/packets/game/State.cpp
  tools/updater/src/Downloader.cpp
  tools/updater/src/main.cpp
  tools/updater/trans/updater_en_US.ts
  tools/updater/trans/updater_ja_JP.ts
  tools/updater/trans/updater_ru_RU.ts
Labels: bug, code, enhancement

#1266 Corrected critical hits not occuring if target Critical Defense turne…
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1271 [FIX] CI should only download again if the cache files do not match the checksum.
  .travis.yml
  ci/checksums/OpenSSL-1_1_1c-win64.msi.sha1
  ci/checksums/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz.sha1
  ci/checksums/cmake-3.6.1-Linux-x86_64.tar.gz.sha1
  ci/checksums/doxygen.zip.sha1
  ci/checksums/external-0.1.1-clang.tar.bz2.sha1
  ci/checksums/external-0.1.1-gcc5.tar.bz2.sha1
  ci/checksums/external-0.1.1-win32.zip.sha1
  ci/checksums/external-0.1.1-win64.zip.sha1
  ci/checksums/ninja-linux.zip.sha1
  ci/checksums/qt-5.12.3-win32.7z.sha1
  ci/checksums/qt-5.12.3-win64.7z.sha1
  ci/checksums/wix311.exe.sha1
  ci/global.sh
  ci/linux-warmcache.sh
  ci/windows-warmcache.sh
Labels: code, enhancement
