Repository comphack/comp_hack, pull requests merged in 2020-05, with the labels that each got.

#1209 Executive decision changes and fixes
  server/channel/src/ChannelServer.cpp
  server/channel/src/ClientState.h
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/WorldClock.cpp
  server/channel/src/WorldClock.h
  server/channel/src/packets/game/Pivot.cpp
  server/channel/src/packets/game/ShopBuy.cpp
  server/channel/src/packets/game/ShopData.cpp
  server/channel/src/packets/game/SkillActivate.cpp
  server/channel/src/packets/game/SkillCancel.cpp
  server/channel/src/packets/game/SkillExecute.cpp
  server/channel/src/packets/game/SkillExecuteInstant.cpp
  server/channel/src/packets/game/SkillTarget.cpp
  server/lobby/src/packets/game/CharacterList.cpp
  server/world/src/AccountManager.cpp
Labels: bug, enhancement

#1210 More accurate negotiation "progression", collision and bug fixes
  server/channel/src/AIManager.cpp
  server/channel/src/CharacterManager.cpp
  server/channel/src/EnemyState.cpp
  server/channel/src/EnemyState.h
  server/channel/src/SkillManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
  server/channel/src/packets/game/Move.cpp
Labels: bug

#1213 QMP support for bdpatch and double tarot/soul fix
  server/channel/src/CharacterManager.cpp
  tools/bdpatch/src/main.cpp
Labels: bug, enhancement

#1214 v4.12.0 Wyrd
  CMakeLists.txt
  README.md
  debian/changelog
Labels: code
