Repository comphack/comp_hack, pull requests merged in 2020-03, with the labels that each got.

#1153 More AI scripting options, AI following and overdue skill restrictions
  contrib/winconfig/newcharacter.xml
  docs/guide/setup/config/worldsharedconfig.xml
  server/channel/schema/aistate.xml
  server/channel/src/AIManager.cpp
  server/channel/src/AIManager.h
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/ChannelServer.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/ZoneManager.cpp
  server/channel/src/ZoneManager.h
Labels: bug, enhancement

#1154 [FIX] Revert the CI back (workflows is NOT ready).
  .github/workflows/.ci_next
  .github/workflows/ci.yml
  .travis.yml
  ci/windows-build.sh
  ci/windows-warmcache.sh
Labels: enhancement

#1156 Adjust item useSkill restrictions, misc fixes
  docs/guide/setup/config/lobby.xml
  server/channel/src/ChatManager.cpp
  server/channel/src/SkillManager.cpp
  server/channel/src/SkillManager.h
  server/channel/src/ZoneManager.cpp
  server/lobby/schema/lobbyconfig.xml
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
  server/lobby/src/ImportHandler.cpp
Labels: bug

#1157 Including digi skills in restriction check, fixing null reference from quest deletion
  server/channel/src/AccountManager.cpp
  server/channel/src/SkillManager.cpp
Labels: bug

#1158 v4.10.0 Ingwaz
  CMakeLists.txt
  README.md
  debian/changelog
Labels: enhancement

#1161 Proper fix for diaspora base state upon relog
  server/channel/src/MatchManager.cpp
  server/channel/src/ZoneManager.cpp
Labels: bug
