Repository comphack/comp_hack, pull requests merged in 2020-02, with the labels that each got.

#1139 [FIX] Qt online installer no longer works because they want to be forked.
  ci/global.sh
  ci/qt-installer-windows.qs
  ci/travis-cache-windows.sh
  ci/travis-install-qt-windows.sh
  ci/windows-build.sh
  ci/windows-updater.sh
  ci/windows-warmcache.sh
Labels: bug

#1140 Correcting digi HP/MP calc, properly using active skill stats, fixing runtime failures
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/ActiveEntityState.h
  server/channel/src/AllyState.cpp
  server/channel/src/AllyState.h
  server/channel/src/CharacterState.cpp
  server/channel/src/CharacterState.h
  server/channel/src/DemonState.cpp
  server/channel/src/DemonState.h
  server/channel/src/EnemyState.cpp
  server/channel/src/EnemyState.h
  server/channel/src/SkillManager.cpp
  server/channel/src/Zone.cpp
  server/channel/src/Zone.h
  server/channel/src/packets/game/SearchAppReply.cpp
  server/lobby/src/ApiHandler.cpp
  server/lobby/src/ApiHandler.h
Labels: bug

#1141 [ADD] Initial workflow to build the project on GitHub.
  .github/workflows/.ci_next
  .github/workflows/automerge.yml
  .github/workflows/ci.yml
  .travis.yml
  ci/github-linux.sh
  ci/github-win32.ps1
  ci/github-win64.ps1
  server/channel/src/ActiveEntityState.cpp
  server/channel/src/packets/game/ItemPrice.cpp
Labels: automerge, enhancement

#1142 Fixing status double expiration issue
  server/channel/src/ActiveEntityState.cpp
Labels: bug

#1143 v4.9.0 Nauthiz
  CMakeLists.txt
  README.md
  debian/changelog
Labels: automerge, code

#1144 [MOD] Remove the automerge workflow and fix the documentation tag action.
  .github/workflows/automerge.yml
  .github/workflows/ci.yml
Labels: code
