Repository comphack/comp_hack, pull requests merged in 2021-07, with the labels that each got.

#1426 [FIX] Mitama fusion was not saving the resulting mitama demon to the DB.
  server/channel/src/FusionManager.cpp
Labels: bug, code

#1417 Prevent crash by null reference if attempting to move an invalid demon to another slot.
  server/channel/src/packets/game/DemonBoxMove.cpp
Labels: bug, code

#1393 DAMAGE_TAKEN tokusei calculated correctly.
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1390 Squirrel bindings for GetDefinitionManager and GetItemData.
  libhack/schema/binarydata/enchantdata.xml
  libhack/src/DefinitionManager.cpp
  server/channel/src/ChannelServer.cpp
  server/channel/src/EventManager.cpp
  server/channel/src/EventManager.h
  server/channel/src/SkillManager.cpp
Labels: code, enhancement

#1413 Minion spawns appear 200 units from master if no spotID specified.
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1403 Fix for Demon Equipment destruction if move attempted mid-prompt.
  server/channel/src/packets/game/DemonEquip.cpp
Labels: bug, code

#1404 Fix for Demon Partner resurrection errors.
  server/channel/src/ActiveEntityState.h
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1307 Make Traesto skills not assume self-targeting.
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1410 Feature to configure Rebirth Extraction behavior.
  contrib/testing/config/constants.xml
  docs/guide/chapters/config.rst
  libhack/schema/demon.xml
  libhack/schema/worldsharedconfig.xml
  libhack/src/ServerConstants.cpp
  libhack/src/ServerConstants.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/packets/game/ReunionExtract.cpp
Labels: enhancement, feature request

#1428 [ADD] Support for creating a pak with comp_translator
  tools/translator/CMakeLists.txt
  tools/translator/src/translator.cpp
Labels: code, enhancement

#1431 [ADD] Client patch (DLL) enforcement settings
  docs/guide/chapters/config.rst
  libhack/src/PacketCodes.h
  server/lobby/CMakeLists.txt
  server/lobby/schema/clientstate.xml
  server/lobby/schema/lobbyconfig.xml
  server/lobby/src/LobbyServer.cpp
  server/lobby/src/Packets.h
  server/lobby/src/packets/amala/AppliedPatches.cpp
  server/lobby/src/packets/game/Auth.cpp
  server/lobby/src/packets/game/StartGame.cpp
  tools/updater/src/ClientPatches.cpp
  tools/updater/src/ClientPatches.h
  tools/updater/src/Downloader.cpp
  tools/updater/src/Options.cpp
  tools/updater/src/Options.h
Labels: code, enhancement

#1430 [ADD] New DLL patches to the updater options
  tools/updater/src/ClientPatches.cpp
  tools/updater/src/ClientPatches.h
  tools/updater/src/Options.cpp
  tools/updater/ui/Options.ui
Labels: code, enhancement

#1429 [FIX] Ensure all fusion DB operations are in the same changeset.
  server/channel/src/CharacterManager.cpp
  server/channel/src/CharacterManager.h
  server/channel/src/FusionManager.cpp
  server/channel/src/FusionManager.h
Labels: bug, code

#1432 [FIX] Parsing of channel login packet.
  server/channel/src/packets/game/Login.cpp
Labels: bug, code

#1433 Delay targeted Traesto by 0.1s
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1435 Start Rebirth Injection costs at the rank the demon is rising to.
  server/channel/src/packets/game/ReunionInject.cpp
Labels: bug, code

#1438 [ADD] Optional plugin requirement for Fusion Mistakes.
  libhack/schema/fusion.xml
  server/channel/src/FusionManager.cpp
  server/channel/src/FusionManager.h
Labels: code, enhancement, feature request

#1436 Add new AIState of ENRAGED
  server/channel/src/AIManager.cpp
  server/channel/src/AIState.cpp
  server/channel/src/AIState.h
  server/channel/src/CharacterManager.cpp
  server/channel/src/SkillManager.cpp
Labels: bug, code

#1439 [ADD] Ability for certain GM commands to target another character
  server/channel/src/ChatManager.cpp
  server/channel/src/EventManager.cpp
Labels: code, feature request

#1437 Add server-side quest and valuable checks for the use of warp points.
  libhack/CMakeLists.txt
  libhack/schema/binarydata/warppointdata.xml
  server/channel/src/packets/game/Warp.cpp
Labels: bug, code
